project_id = "pokedgheskrgmerrwlfj"

[functions.analyze-content]
verify_jwt = false

[functions.generate-cover]
verify_jwt = false

[functions.generate-ideas]
verify_jwt = false

[functions.generate-draft]
verify_jwt = false

[functions.generate-feed]
verify_jwt = false
